# -*- coding: utf-8 -*-
"""Latihan AI | Regan Pratama Banyuadji

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKoR0lt1EhkZgvCEG7wGvuiEmE-DG98i

# gah


str_numbers = "456"
str_numbers_to_int = int(str_numbers)
print("Before casting :", str_numbers, ", the data type is",
type(str_numbers))
print("After casting :", str_numbers_to_int, ", the data type is",
type(str_numbers_to_int))
"""

print(30*"=")
print("Identification Program")
print(30*"=")
name = str(input("What is your name : "))
age = int(input("What's your age : "))
print("Name: ", name)
print("Age: ", age)

# normal print
print('Hi all! I am', name, 'age', age, 'years old')
# format print
print(f'Hi all! I am {name} age {age} years old')
# format print
print(f'Hi all! I am %s age %d years old'%(name, age))

e = 8
f = 2
print(30*"=")
print("Calculation Program")
print(30*"=")
# Summation
sum = e + f
print(f"The sum of e with f is : {sum}\n")
# Reduction
red = e - f
print(f"The reduction of e with f is : {red}\n")

# Multiplication
multi = e * f
print(f"The multipication of e with f is : {multi}\n")
# Division
divi = e / f
print(f"The quotient of e with f is : {divi}\n")
# Modulo
mod = e % f
print(f"The remainder of e with f is : {mod}\n")
# Power
pow = e ** f
print(f"The power of e of f is : {pow}\n")

print(30*"=")
print("Other Interactible Programs")
print(30*"=")
try:
    your_GPA = float(input("Enter your GPA: "))
    if 4.0 >= your_GPA >= 0.0:
        if 4.0 >= your_GPA >= 3.80:
            print(f"You receive a magna cumlaude with your {your_GPA} GPA")
        elif 3.50 <= your_GPA < 3.80:
            print(f"You receive a cumlaude with your {your_GPA} GPA")
        elif 3.00 <= your_GPA < 3.50:
            print(f"You have a stable GPA")
        elif your_GPA < 3.0:
            print(f"You need a stable GPA")
    else:
        print(f"Sorry, your GPA {your_GPA} is out of range and invalid")
except:

    print("Please enter a valid GPA")

try:
    status_code = int(input("Enter your status code: "))
    print("Your code means")
    match status_code:
        case 200:
            print("Success!")
        case 400:
            print("Bad Request")
        case 401:
            print("Unauthorized")
        case 402:
            print("Payment Required")
        case 403:
            print("Forbidden")
        case 404:
            print("Not Found")
        case 500:
            print("Internal Server Error")
except :
    print("Please enter a valid status code")


a = int(input("Insert any number: "))
b = "Even Numbers" if a % 2 == 0 else "Odd Numbers"
print(b)

print(30*"=")
print("Casting Program")
print(30*"=")
# cast from str to int
str_numbers = "456"
str_numbers_to_int = int(str_numbers)
print("Before casting :", str_numbers, ", the data type is",
type(str_numbers))
print("After casting :", str_numbers_to_int, ", the data type is",
type(str_numbers_to_int))


# casting from int to str
integer = 12345
integer_to_str = str(integer)
print("Before casting :", integer, ", the data type is", type(integer))
print("After casting :", integer_to_str, ", the data type is",
type(integer_to_str))

# casting from int to bool
num_int = 1
num_bool = bool(num_int)
print(num_bool, type(num_bool))
num_int = 0

num_bool = bool(num_int)
print(num_bool, type(num_bool))

# Equal to
8 == 8
# Not equal to
8 != 9
# Greater than
8 > 9
# Less than
8 < 9
# Less than
8 <= 9
# Less than
9 >= 9

a = True
b = True
print(a and b)
print(a or b)
print(not b)
#logic
5 > 6 and 6 < 7